import type { Metadata } from "next";
import { Inter, Chakra_Petch } from "next/font/google";
import localfont from "next/font/local";
import Structure from "@/components/structure";
import { SpeedInsights } from "@vercel/speed-insights/next"
import Script from "next/script";
import ClientErrorLogger from "@/components/ClientErrorLogger";
 
export const metadata: Metadata = {
  title: 'Winter of Code 5.0',
  description: 'Loading...',
};

const inter = Inter({ subsets: ["latin"] });
const chakra = Chakra_Petch({
  subsets: ["latin"] , 
  weight: "400",
  variable: "--font-chakra"
});

const kleemax = localfont({
  src : [{
    path: "../public/fonts/kleemaxdemo.ttf",
    weight : "400"
    }],
    variable: "--font-kleemax"
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${kleemax.variable} ${chakra.variable} bg-black`}>
        <ClientErrorLogger />
        {/* <Structure children={children}/> */}
        <Structure>{children}</Structure>
        {/* <script defer async src="https://apply.devfolio.co/v2/sdk.js"></script> */}
        <Script src="https://apply.devfolio.co/v2/sdk.js" strategy="afterInteractive" />
        <SpeedInsights />
      </body>
    </html>
  );
}
